development:
  adapter: postgresql
  encoding: unicode
  database: inventory_development
  pool: 5
  host: localhost
  username: username
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: inventory_test
  pool: 5
  username: username
  password: password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>